import { Room, Role, User, Language } from './types';

export const ROLES: { [key in Role]: { name: string, color: string, darkColor: string } } = {
  [Role.ADMIN]: { name: 'Admin', color: 'text-admin', darkColor: 'dark:text-admin-dark' },
  [Role.MODERATOR]: { name: 'Moderator', color: 'text-moderator', darkColor: 'dark:text-moderator-dark' },
  [Role.USER]: { name: 'User', color: 'text-user', darkColor: 'dark:text-user-dark' },
};

export const INITIAL_ROOMS: Room[] = [
  { id: '1', name: 'General Chat', isPrivate: false, color: '#3b82f6' },
  { id: '2', name: 'Tech Talk', isPrivate: false, color: '#10b981' },
  { id: '3', name: 'Gaming Zone', isPrivate: false, color: '#8b5cf6' },
  { id: '4', name: 'Private Lounge', isPrivate: true, password: 'password123', color: '#ef4444' },
];

export const DEFAULT_PROFILE_PICTURE = 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0iY3VycmVudENvbG9yIiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIGNsYXNzPSJmaWxsLWdyYXktNDAwIj4KICA8cGF0aCBkPSJNMTIgMTEuNXE3NS0uMjUgMS40MzgtLjg3NVQxNC41IDEwLjVxLjYyNS0uNzUgMS0xLjg3NVQxNS41IDZzMC0yLjM3NS0xLjI1LTMuNjg3VDExLjUgMS41cS0xLjM3NS4zNzUtMi4yNSAxLjQzN1Q4LjUgNnMwIDEuNzUuMzc1IDIuODc1VDEwLjI1IDEwLjVxLjM3NS4zNzUgMS4wNjMgLjg3NVQxMiAxMS41Wm0wIDRxLTMuMzUgMC01LjkyNSAxLjY1VDIuNSAyaDE5cS0xLjI1LTMuMy0zLjY3NS00Ljk1VDExLjk5OSA4LjY3NnoiLz4KPC9zdmc+Cg==';

export const ADMIN_USER: User = { id: 'admin-user', nickname: 'Admin', role: Role.ADMIN, password: 'admin', profilePicture: DEFAULT_PROFILE_PICTURE };
export const BOT_USER: User = { id: 'bot-user', nickname: 'GeminiBot', role: Role.MODERATOR, color: '#3b82f6', profilePicture: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgMjQgMjQiPjxwYXRoIGZpbGw9IiM4ODg4ODg4IiBkPSJNMTEuMjUgNC41YTUuMjUgNS4yNSAwIDAgMC01LjI0IDEuMjVMMi4yNjUgMS4yNjVhLjc1Ljc1IDAgMCAwLTEuMDYgMS4wNkw1Ljk5IDcuMDlhNS4yNSA1LjI1IDAgMSAwIDUuMjYtMi41OWptMCA4LjVhMy43NSAzLjM3NSAwIDAgMSAwIDcuNVptNy41IDMuNzVhNS4yNSA1LjI1IDAgMCAwIDEuMjUtNS4yNEwxNS4yNjYgNy4yNjVhLjc1Ljc1IDAgMSAwLTEuMDYyLTEuMDYxbDQuNzggNC43ODFhNS4yNSA1LjI1IDAgMSAwIDAgMi41OVoiLz48L3N2Zz4=' };

export const ROOM_COLORS = ['#3b82f6', '#10b981', '#ef4444', '#f97316', '#8b5cf6', '#d946ef', '#06b6d4', '#84cc16', '#f59e0b', '#ec4899', '#22c55e', '#64748b'];

export const TRANSLATIONS: { [lang in Language]: { [key: string]: string } } = {
  ar: {
    welcome: 'مرحبا بك في ChatZone',
    selectLanguage: 'الرجاء اختيار لغتك',
    enterNickname: 'أدخل اسمك المستعار',
    nickname: 'الاسم المستعار',
    join: 'انضمام',
    adminLogin: 'تسجيل الدخول كمدير',
    modLogin: 'تسجيل الدخول كمشرف',
    rooms: 'غرف الدردشة',
    joinRoom: 'الانضمام للغرفة',
    leaveRoom: 'مغادرة الغرفة',
    enterPassword: 'أدخل كلمة المرور لـ',
    password: 'كلمة المرور',
    submit: 'إرسال',
    cancel: 'إلغاء',
    sendMessage: 'أرسل رسالة...',
    usersInRoom: 'المستخدمون في الغرفة',
    kick: 'طرد',
    ban: 'حظر',
    mute: 'كتم',
    delete: 'حذف',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    send: 'إرسال',
    kicked: 'لقد تم طردك من الغرفة.',
    incorrectPassword: 'كلمة المرور غير صحيحة.',
    roomIsFull: 'هذه الغرفة ممتلئة.',
    createRoom: 'إنشاء غرفة',
    newRoom: 'غرفة جديدة',
    roomName: 'اسم الغرفة',
    privateRoom: 'غرفة خاصة',
    create: 'إنشاء',
    report: 'إبلاغ',
    reportMessageConfirmation: 'تم الإبلاغ عن الرسالة. سيقوم المشرفون بمراجعتها.',
    adminPanel: 'لوحة الإدارة',
    moderationPanel: 'لوحة الإشراف',
    manageModerators: 'المشرفون',
    addModerator: 'إضافة مشرف',
    moderatorName: 'اسم المشرف',
    moderatorPassword: 'كلمة مرور المشرف',
    moderatorColor: 'اللون',
    remove: 'إزالة',
    startPrivateChat: 'بدء محادثة خاصة',
    directMessages: 'الرسائل المباشرة',
    backToRooms: 'العودة إلى الغرف',
    selectAvatar: 'اختر صورتك الرمزية',
    continue: 'متابعة',
    reports: 'البلاغات',
    gallery: 'معرض الصور',
    reportedMessage: 'الرسالة المبلغ عنها',
    reportedBy: 'المبلغ',
    dismiss: 'تجاهل',
    deleteMessage: 'حذف الرسالة',
    noReports: 'لا توجد بلاغات معلقة.',
    addImage: 'إضافة صورة',
    imageUrl: 'رابط الصورة',
    add: 'إضافة',
    noImages: 'لا توجد صور مخصصة في المعرض حتى الآن.',
    roomColor: 'لون الغرفة',
    logout: 'تسجيل الخروج',
    back: 'العودة',
    adminPassword: 'كلمة مرور المدير',
    settings: 'الإعدادات',
    changeAdminPassword: 'تغيير كلمة مرور المدير',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة.',
    passwordChangedSuccessfully: 'تم تغيير كلمة المرور بنجاح.',
    incorrectAdminPassword: 'كلمة مرور المدير غير صحيحة.',
    passwordTooShort: 'يجب أن تتكون كلمة المرور من 4 أحرف على الأقل.',
    banUser: 'حظر المستخدم',
    bannedUntil: 'أنت محظور حتى',
    youAreBanned: 'أنت محظور من الدردشة.',
    banDuration: 'مدة الحظر',
    '15m': '15 دقيقة',
    '30m': '30 دقيقة',
    '12h': '12 ساعة',
    bannedUsers: 'المستخدمون المحظورون',
    unban: 'رفع الحظر',
    noBannedUsers: 'لا يوجد مستخدمون محظورون حاليًا.',
  }
};